name: terraform
version: "1.1.9"
summary: Terraform enables you to create, change, and improve infrastructure.
description: |
  Terraform enables you to safely and predictably create, change, and improve
  infrastructure. It is an open source tool that codifies APIs into
  declarative configuration files that can be shared amongst team members,
  treated as code, edited, reviewed, and versioned.
base: core20
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

parts:
  terraform:
    plugin: dump
    source:
      - on amd64: https://releases.hashicorp.com/terraform/$SNAPCRAFT_PROJECT_VERSION/terraform_$SNAPCRAFT_PROJECT_VERSION_linux_amd64.zip
      - on i386: https://releases.hashicorp.com/terraform/$SNAPCRAFT_PROJECT_VERSION/terraform_$SNAPCRAFT_PROJECT_VERSION_linux_386.zip
      - on armhf: https://releases.hashicorp.com/terraform/$SNAPCRAFT_PROJECT_VERSION/terraform_$SNAPCRAFT_PROJECT_VERSION_linux_arm.zip
      - on arm64: https://releases.hashicorp.com/terraform/$SNAPCRAFT_PROJECT_VERSION/terraform_$SNAPCRAFT_PROJECT_VERSION_linux_arm64.zip
    stage:
      - terraform

apps:
  terraform:
    command: terraform
    environment:
      TF_PLUGIN_CACHE_DIR: $HOME/.terraform.d/plugin-cache
    plugs:
      - home
      - network
      - network-bind
      - dot-terraformrc
      - dot-terraform-d
      - kube-credentials
      - aws-credentials
      - azure-credentials
      - gcp-credentials

plugs:
  dot-terraformrc:
    interface: personal-files
    read:
      - $HOME/.terraformrc
  dot-terraform-d:
    interface: personal-files
    read:
      - $HOME/.terraform.d
    write:
      - $HOME/.terraform.d

  kube-credentials:
    interface: personal-files
    read:
      - $HOME/.kube/config
  aws-credentials:
    interface: personal-files
    read:
      - $HOME/.aws
  gcp-credentials:
    interface: personal-files
    read:
      - $HOME/.config/gcloud
  azure-credentials:
    interface: personal-files
    read:
      - $HOME/.azure
