name: terraform
version: "1.1.9"
summary: Terraform enables you to create, change, and improve infrastructure.
description: |
  Terraform enables you to safely and predictably create, change, and improve
  infrastructure. It is an open source tool that codifies APIs into
  declarative configuration files that can be shared amongst team members,
  treated as code, edited, reviewed, and versioned.
base: core22
grade: stable
confinement: classic
compression: lzo

apps:
  terraform:
    command: terraform

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: s390x
  - build-on: ppc64el

parts:
  terraform:
    plugin: go
    source: https://github.com/hashicorp/terraform
    source-type: git
    source-tag: "v$SNAPCRAFT_PROJECT_VERSION"
    build-environment:
      - CGO_ENABLED: "0"
      - GOFLAGS: "-mod=readonly"
    override-build: |
      go mod download
      go build -ldflags "-s -w"
      cp terraform $SNAPCRAFT_PART_INSTALL/terraform
    stage:
      - terraform
