name: Build and Test

on:
  workflow_call:
    outputs:
      snap:
        description: "Filename of the built snap"
        value: ${{ jobs.main.outputs.snap }}

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build snap locally
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload locally built snap artifact
        uses: actions/upload-artifact@v3
        with:
          name: local-${{ steps.snapcraft.outputs.snap }}
          path: ${{ steps.snapcraft.outputs.snap }}

      - name: Install snap & invoke terraform
        run: |
          sudo snap install --dangerous --classic ${{ steps.snapcraft.outputs.snap }}
          terraform --version

      - name: Setup MicroK8s
        uses: balchua/microk8s-actions@v0.2.1

      - name: Setup Docker
        run: |
          sudo snap install docker
          sudo addgroup --system docker; sudo adduser $USER docker
          newgrp docker
          sudo snap disable docker; sudo snap enable docker

      - name: Test snap - Kubernetes
        run: |
          terraform -chdir=test/kubernetes init
          terraform -chdir=test/kubernetes apply -auto-approve
          kubectl get ns snaptest

      - name: Test snap - Docker
        run: |
          terraform -chdir=test/docker init
          terraform -chdir=test/docker apply -auto-approve

          # Loop until we can reach the container we just created
          while ! curl -s localhost:8000; do
            # If unsuccessful wait for 5 secs before retrying
            sleep 5
            ((i++))

            # If this is our 10th attempt, bail with an error
            if [[ $i -gt 10 ]]; then
              echo "Unable to reach container"
              exit 1
            fi
          done
