name: Push (main)

on:
  push:
    branches:
      - main
    paths:
      - "snap/snapcraft.yaml"
      - ".github/workflows/**.yaml"

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml

  # Uncomment when the snap confinement/plugs are configured
  publish:
    # Prevent this job from running concurrently so we don't spam launchpad
    concurrency: lp-remote-build
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup snapcraft
        env:
          LP_BUILD_SECRET: ${{ secrets.LP_BUILD_SECRET }}
          STORE_LOGIN: ${{ secrets.STORE_LOGIN }}
        run: |
          # Install snapcraft
          sudo snap install snapcraft --classic --channel=7.x/candidate

          # Login to snapcraft using saved credentials
          echo "$STORE_LOGIN" > credentials.txt
          snapcraft login --with credentials.txt

          # Setup Launchpad credentials
          mkdir -p ~/.local/share/snapcraft/provider/launchpad
          echo "$LP_BUILD_SECRET" > ~/.local/share/snapcraft/provider/launchpad/credentials
          git config --global user.email "github-actions@github.com"
          git config --global user.name "Github Actions"

      - name: Remote build the snap
        run: snapcraft remote-build --launchpad-accept-public-upload

      - name: Upload remote build snap artifacts and build logs
        uses: actions/upload-artifact@v3
        with:
          name: remote-build-snaps
          path: |
            **/*.snap
            **/*.txt

      - name: Upload and release (edge, candidate)
        run: |
          # Get the current version of the snap
          VERSION="$(grep -Po "^version: \"\K[0-9]+\.[0-9]+\.[0-9]+" snap/snapcraft.yaml)"

          # Upload the snaps and release to edge, candidate
          snapcraft upload --release edge,candidate "terraform_${VERSION}_amd64.snap"
          snapcraft upload --release edge,candidate "terraform_${VERSION}_arm64.snap"
          snapcraft upload --release edge,candidate "terraform_${VERSION}_armhf.snap"
          snapcraft upload --release edge,candidate "terraform_${VERSION}_s390x.snap"
          snapcraft upload --release edge,candidate "terraform_${VERSION}_ppc64el.snap"
